from gamecovers_widgets import *

class AppShell(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title(f"{APP_NAME} {APP_VERSION}")
        self.geometry("1280x820")
        self.minsize(1100, 720)
        self.configure(bg="#0b1220")

        self.folder = tk.StringVar()
        self.api_key = tk.StringVar()
        self.status = tk.StringVar(value="Ready.")
        self.hide_shields = tk.BooleanVar(value=True)
        self.hide_arrows = tk.BooleanVar(value=True)
        self.found_var = tk.StringVar(value="0")
        self.skipped_var = tk.StringVar(value="0")
        self.total_var = tk.StringVar(value="0")
        self.progress_var = tk.StringVar(value="0%")
        self.items = []
        self.overrides = {}
        self.logs = []
        self.preview_ref = None
        self.running = False
        self.last_cache = None

        self._setup_styles()
        self._build_ui()

    def _setup_styles(self):
        style = ttk.Style(self)
        style.theme_use("clam")
        style.configure("Base.TFrame", background="#0b1220")
        style.configure("Card.TFrame", background="#111b2d", borderwidth=1, relief="solid")
        style.configure("Panel.TFrame", background="#0f1728")
        style.configure("Title.TLabel", background="#0b1220", foreground="#eaf2ff", font=("Segoe UI", 20, "bold"))
        style.configure("HeroTitle.TLabel", background="#0b1220", foreground="#80b8ff", font=("Segoe UI", 28, "bold"))
        style.configure("Sub.TLabel", background="#0b1220", foreground="#a9bad6", font=("Segoe UI", 10))
        style.configure("Section.TLabel", background="#111b2d", foreground="#eaf2ff", font=("Segoe UI", 10, "bold"))
        style.configure("Field.TLabel", background="#111b2d", foreground="#d6e5ff", font=("Segoe UI", 9, "bold"))
        style.configure("Info.TLabel", background="#111b2d", foreground="#9db0cf", font=("Segoe UI", 9))
        style.configure("StatValue.TLabel", background="#121f34", foreground="#ffffff", font=("Segoe UI", 18, "bold"))
        style.configure("StatName.TLabel", background="#121f34", foreground="#a8bbd8", font=("Segoe UI", 9))
        style.configure("TLabel", background="#0b1220", foreground="#e5eeff")
        style.configure("TButton", font=("Segoe UI", 10), padding=7)
        style.configure("Accent.TButton", font=("Segoe UI", 11, "bold"), padding=10)
        style.map("Accent.TButton", background=[("!disabled", "#5c6cff"), ("pressed", "#4a58d8"), ("active", "#6a79ff")], foreground=[("!disabled", "white")])
        style.configure("TEntry", fieldbackground="#0d1524", foreground="#eff5ff", insertcolor="#eff5ff")
        style.configure("TLabelframe", background="#111b2d", foreground="#eaf2ff")
        style.configure("TLabelframe.Label", background="#111b2d", foreground="#d8e7ff", font=("Segoe UI", 10, "bold"))
        style.configure("Treeview", background="#0d1625", fieldbackground="#0d1625", foreground="#edf3ff", rowheight=28, bordercolor="#263858")
        style.map("Treeview", background=[("selected", "#294d7a")], foreground=[("selected", "white")])
        style.configure("Treeview.Heading", background="#152338", foreground="#ecf4ff", font=("Segoe UI", 10, "bold"), relief="flat")
        style.configure("Vertical.TScrollbar", background="#182640", troughcolor="#0d1524")
        style.configure("TCheckbutton", background="#111b2d", foreground="#eaf2ff")

    def _build_ui(self):
        self.columnconfigure(1, weight=1)
        self.rowconfigure(0, weight=1)

        left = ttk.Frame(self, style="Card.TFrame", padding=16)
        left.grid(row=0, column=0, sticky="ns", padx=(14, 8), pady=14)
        left.configure(width=330)
        left.grid_propagate(False)
        left.columnconfigure(0, weight=1)

        ttk.Label(left, text=APP_NAME, style="Title.TLabel").grid(row=0, column=0, sticky="w")
        ttk.Label(left, text="Turn Windows shortcuts into a clean game-cover library.", style="Sub.TLabel").grid(row=1, column=0, sticky="w", pady=(0, 16))

        folder_frame = ttk.LabelFrame(left, text="1. Shortcut folder", padding=12)
        folder_frame.grid(row=2, column=0, sticky="ew", pady=(0, 12))
        folder_frame.columnconfigure(0, weight=1)
        ttk.Entry(folder_frame, textvariable=self.folder).grid(row=0, column=0, sticky="ew")
        ttk.Button(folder_frame, text="Browse…", command=self.pick_folder).grid(row=0, column=1, padx=(8, 0))
        ttk.Label(folder_frame, text="Pick the folder that contains your .lnk game shortcuts.", style="Info.TLabel").grid(row=1, column=0, columnspan=2, sticky="w", pady=(8, 0))

        key_frame = ttk.LabelFrame(left, text="2. SteamGridDB API key", padding=12)
        key_frame.grid(row=3, column=0, sticky="ew", pady=(0, 12))
        key_frame.columnconfigure(0, weight=1)
        self.key_entry = ttk.Entry(key_frame, textvariable=self.api_key, show="•")
        self.key_entry.grid(row=0, column=0, sticky="ew")
        ttk.Button(key_frame, text="Show/Hide", command=self.toggle_key).grid(row=0, column=1, padx=(8, 0))
        ttk.Button(key_frame, text="Open Preferences", command=self.open_preferences).grid(row=1, column=0, columnspan=2, sticky="ew", pady=(8, 0))

        options = ttk.LabelFrame(left, text="3. Options", padding=12)
        options.grid(row=4, column=0, sticky="ew", pady=(0, 12))
        ttk.Checkbutton(options, text="Remove Windows shortcut arrows", variable=self.hide_arrows).pack(anchor="w")
        ttk.Checkbutton(options, text="Hide UAC shield using smart launcher", variable=self.hide_shields).pack(anchor="w", pady=(6, 0))
        ttk.Label(options, text="Games still launch normally and elevation behavior is preserved.", style="Info.TLabel").pack(anchor="w", pady=(8, 0))

        manual_frame = ttk.LabelFrame(left, text="4. Manual covers", padding=12)
        manual_frame.grid(row=5, column=0, sticky="ew", pady=(0, 12))
        ttk.Button(manual_frame, text="Manage / Replace Covers", command=self.open_cover_manager).pack(fill="x")
        ttk.Button(manual_frame, text="Open Overrides File", command=self.open_overrides).pack(fill="x", pady=(8, 0))
        ttk.Button(manual_frame, text="Restore Shortcut Arrows", command=self.restore_arrows_clicked).pack(fill="x", pady=(8, 0))
        ttk.Label(manual_frame, text="Choose your own cover for any game — found or skipped. Custom choices are saved and reused.", style="Info.TLabel", wraplength=280, justify="left").pack(anchor="w", pady=(8, 0))

        left.rowconfigure(6, weight=1)
        helper = ttk.Label(left, text="Tip: set Windows Explorer to Extra Large Icons for the cleanest look.", style="Sub.TLabel", wraplength=280, justify="left")
        helper.grid(row=6, column=0, sticky="sw", pady=(12, 0))

        right = ttk.Frame(self, style="Base.TFrame")
        right.grid(row=0, column=1, sticky="nsew", padx=(0, 14), pady=14)
        right.columnconfigure(0, weight=3)
        right.columnconfigure(1, weight=2)
        right.rowconfigure(2, weight=1)
        right.rowconfigure(3, weight=1)

        ttk.Label(right, text=APP_NAME, style="HeroTitle.TLabel").grid(row=0, column=0, sticky="w")
        ttk.Label(right, text="High-quality portrait covers. Smarter matching. Simple workflow.", style="Sub.TLabel").grid(row=0, column=1, sticky="e")

        stats_bar = ttk.Frame(right, style="Base.TFrame")
        stats_bar.grid(row=1, column=0, columnspan=2, sticky="ew", pady=(10, 12))
        for i in range(4):
            stats_bar.columnconfigure(i, weight=1)
        self._make_stat(stats_bar, 0, "Total", self.total_var)
        self._make_stat(stats_bar, 1, "Found", self.found_var)
        self._make_stat(stats_bar, 2, "Skipped", self.skipped_var)
        self._make_stat(stats_bar, 3, "Progress", self.progress_var)

        results_card = ttk.Frame(right, style="Card.TFrame", padding=12)
        results_card.grid(row=2, column=0, sticky="nsew", padx=(0, 10), pady=(0, 10))
        results_card.columnconfigure(0, weight=1)
        results_card.rowconfigure(1, weight=1)
        ttk.Label(results_card, text="Results", style="Section.TLabel").grid(row=0, column=0, sticky="w", pady=(0, 8))
        cols = ("name", "status", "source", "details")
        self.tree = ttk.Treeview(results_card, columns=cols, show="headings")
        self.tree.heading("name", text="Game")
        self.tree.heading("status", text="Status")
        self.tree.heading("source", text="Source")
        self.tree.heading("details", text="Notes")
        self.tree.column("name", width=220)
        self.tree.column("status", width=90, anchor="center")
        self.tree.column("source", width=150)
        self.tree.column("details", width=340)
        self.tree.grid(row=1, column=0, sticky="nsew")
        sb1 = ttk.Scrollbar(results_card, orient="vertical", command=self.tree.yview)
        sb1.grid(row=1, column=1, sticky="ns")
        self.tree.configure(yscrollcommand=sb1.set)
        self.tree.bind("<<TreeviewSelect>>", self.on_tree_select)

        preview_card = ttk.Frame(right, style="Card.TFrame", padding=12)
        preview_card.grid(row=2, column=1, sticky="nsew", pady=(0, 10))
        preview_card.columnconfigure(0, weight=1)
        preview_card.rowconfigure(1, weight=1)
        ttk.Label(preview_card, text="Preview", style="Section.TLabel").grid(row=0, column=0, sticky="w")
        self.preview_label = ttk.Label(preview_card, text="Select a game to preview its cover.", anchor="center")
        self.preview_label.grid(row=1, column=0, sticky="nsew", pady=(8, 8))
        self.preview_info = tk.Text(preview_card, height=7, bg="#0d1625", fg="#e7efff", insertbackground="#e7efff", bd=0, relief="flat", wrap="word")
        self.preview_info.grid(row=2, column=0, sticky="ew")
        self.preview_info.insert("1.0", "No item selected.")
        self.preview_info.configure(state="disabled")
        ttk.Button(preview_card, text="Choose / Replace This Cover…", command=self.choose_selected_cover).grid(row=3, column=0, sticky="ew", pady=(8, 0))

        log_card = ttk.Frame(right, style="Card.TFrame", padding=12)
        log_card.grid(row=3, column=0, columnspan=2, sticky="nsew")
        log_card.columnconfigure(0, weight=1)
        log_card.rowconfigure(1, weight=1)
        ttk.Label(log_card, text="Activity Log", style="Section.TLabel").grid(row=0, column=0, sticky="w")
        self.log = tk.Text(log_card, height=10, bg="#0d1625", fg="#edf4ff", insertbackground="#edf4ff", bd=0, relief="flat")
        self.log.grid(row=1, column=0, sticky="nsew", pady=(8, 10))
        sb2 = ttk.Scrollbar(log_card, orient="vertical", command=self.log.yview)
        sb2.grid(row=1, column=1, sticky="ns", pady=(8, 10))
        self.log.configure(yscrollcommand=sb2.set)

        footer = ttk.Frame(log_card, style="Base.TFrame")
        footer.grid(row=2, column=0, columnspan=2, sticky="ew")
        footer.columnconfigure(0, weight=1)
        ttk.Label(footer, textvariable=self.status, style="Sub.TLabel").grid(row=0, column=0, sticky="w")
        self.progress = ttk.Progressbar(footer, maximum=100)
        self.progress.grid(row=1, column=0, sticky="ew", pady=(8, 0), padx=(0, 10))
        self.run = ttk.Button(footer, text="Find Covers & Apply Icons", command=self.start, style="Accent.TButton")
        self.run.grid(row=0, column=1, rowspan=2, sticky="e")

    def _make_stat(self, parent, col, label, variable):
        card = tk.Frame(parent, bg="#121f34", bd=1, relief="solid", highlightthickness=0)
        card.grid(row=0, column=col, sticky="ew", padx=(0 if col == 0 else 8, 0))
        ttk.Label(card, textvariable=variable, style="StatValue.TLabel").pack(anchor="w", padx=12, pady=(10, 0))
        ttk.Label(card, text=label, style="StatName.TLabel").pack(anchor="w", padx=12, pady=(0, 10))

